MariscosSanJon/config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :measurement_units
  resources :categories

   root 'welcome#index'

end

MariscosSanJon/app/models/category.rb
class Category < ActiveRecord::Base
	validates_presence_of :name, :message => "El nombre no puede estar en blanco" 
end

MariscosSanJon/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :measurement_unit
  validates_presence_of :name, :message => "El nombre no puede estar en blanco" 
  validates_presence_of :stock, :message => "La existencia no puede estar en blanco" 
  validates_presence_of :measurement_unit_id, :message => "La unidad no puede estar en blanco"
  validates_numericality_of :stock, :only_integer => true, :message => "El campo existencia debe ser un valor numérico"
  validates_uniqueness_of :name, :message => "Este nombre de ingrediente ya existe, ingresa uno diferente"
end

MariscosSanJon/app/models/measurement_unit.rb
class MeasurementUnit < ActiveRecord::Base
	validates_uniqueness_of :name, :message => "Este valor ya está registrado"
	validates_presence_of :name, :message => "El nombre no puede estar en blanco"   
end

MariscosSanJon/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

MariscosSanJon/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Categoría creada exitosamente.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Categoría actualizada exitosamente' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category eliminada exitosamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

MariscosSanJon/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingrediente fue creado correctamente.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingrediente fue actualizado correctamente. ' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingrediente fue eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :stock, :measurement_unit_id)
    end
end

MariscosSanJon/app/controllers/measurement_units_controller.rb
class MeasurementUnitsController < ApplicationController
  before_action :set_measurement_unit, only: [:show, :edit, :update, :destroy]

  # GET /measurement_units
  # GET /measurement_units.json
  def index
    @measurement_units = MeasurementUnit.all
  end

  # GET /measurement_units/1
  # GET /measurement_units/1.json
  def show
  end

  # GET /measurement_units/new
  def new
    @measurement_unit = MeasurementUnit.new
  end

  # GET /measurement_units/1/edit
  def edit
  end

  # POST /measurement_units
  # POST /measurement_units.json
  def create
    @measurement_unit = MeasurementUnit.new(measurement_unit_params)

    respond_to do |format|
      if @measurement_unit.save
        format.html { redirect_to @measurement_unit, notice: 'Unidad de medida creada exitosamente' }
        format.json { render :show, status: :created, location: @measurement_unit }
      else
        format.html { render :new }
        format.json { render json: @measurement_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measurement_units/1
  # PATCH/PUT /measurement_units/1.json
  def update
    respond_to do |format|
      if @measurement_unit.update(measurement_unit_params)
        format.html { redirect_to @measurement_unit, notice: 'Unidad de medida editada correctamente' }
        format.json { render :show, status: :ok, location: @measurement_unit }
      else
        format.html { render :edit }
        format.json { render json: @measurement_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measurement_units/1
  # DELETE /measurement_units/1.json
  def destroy
    @measurement_unit.destroy
    respond_to do |format|
      format.html { redirect_to measurement_units_url, notice: 'Unidad de medida eliminada correctamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measurement_unit
      @measurement_unit = MeasurementUnit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measurement_unit_params
      params.require(:measurement_unit).permit(:name)
    end
end

MariscosSanJon/app/helpers/application_helper.rb
module ApplicationHelper
end

MariscosSanJon/app/helpers/categories_helper.rb
module CategoriesHelper
end

MariscosSanJon/app/helpers/ingredients_helper.rb
module IngredientsHelper

	def measurement_for_select
		MeasurementUnit.all.collect { |c| [c.name, c.id] }
	end
	
end

MariscosSanJon/app/helpers/measurement_units_helper.rb
module MeasurementUnitsHelper
end

MariscosSanJon/app/views/categories/_form.html.erb
  <div class="row"> 
    <div class="col s12">
      <%= form_for(@category) do |f| %>
          <% if @category.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@category.errors.count, "error") %> , el elemento no puede ser guardado</h2>
              <ul class="collection">
                <% @category.errors.each do |attr,msg|  %>
                   <li class="collection-item">  <%=msg%> </li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row ">
              <div class="input-field col s6">
                  <i class="material-icons prefix">account_circle</i>
                  <%= f.text_field :name  ,class: "validate", id: "icon_prefix" %>
                  <label for="icon_prefix">Nombre</label>
              </div>
          </div>
          <div class="actions">
                <%= f.submit "Guardar", :class => "btn waves-effect waves-light category-text"  %> 
          </div>
      <% end %>
    </div>
  </div>



 
      
  
        

MariscosSanJon/app/views/categories/edit.html.erb
<div class="container"> 
	<h5>Editar Categoría</h5>

	<%= render 'form' %>

	<%= link_to 'Mostrar', @category, :class => "waves-effect waves-light btn category-text blue" %> 
	<%= link_to 'Regresar', categories_path,:class => "waves-effect waves-light btn category-text red" %>
</div>

MariscosSanJon/app/views/categories/index.html.erb
<% if(notice) %>
  <div class="card-panel">
        <span class="blue-text text-darken-2"><%= notice %> </span>
  </div>
<% end %>
<div class="container">
  <h4>Categorias</h4>
  <table width="70%">
    <thead>
      <tr>
        <th>Categoría </th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= link_to 'Editar', edit_category_path(category), :class  => "waves-effect waves-light btn category-text blue" %></td>
          <td><%= link_to 'Eliminar', category, method: :delete, data: { confirm: 'Seguro que deseas eliminar?' }, :class => "waves-effect waves-light btn category-text red" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <%= link_to 'Agregar Categoría', new_category_path, :class => "waves-effect waves-light btn category-text" %>
</div>

MariscosSanJon/app/views/categories/new.html.erb
<div class="container"> 
	<h5>Nueva Categoría</h5>

	<%= render 'form' %>

	<%= link_to 'Regresar', categories_path, class: "waves-effect waves-light btn red category-text" %>
</div>

MariscosSanJon/app/views/categories/show.html.erb
<div class="container">
	<% if(notice) %>
		<div class="card-panel">
	      <span class="blue-text text-darken-2"><%= notice %> </span>
		</div>
	<% end  %>

	<h4> Detalles Categoría </h4>
	<strong> Categoría: </strong>
	<%= @category.name %>
	<br>
	<br>
	

	<%= link_to 'Editar', edit_category_path(@category), :class => "waves-effect waves-light btn category-text" %> 
	<%= link_to 'Regresar', categories_path,:class => " waves-effect waves-light btn red category-text" %>
</div>

MariscosSanJon/app/views/ingredients/_form.html.erb
 <%= form_for(@ingredient) do |f| %>
        <% if @ingredient.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

           <ul class="collection">
                <% @ingredient.errors.each do |attr,msg|  %>
                   <li class="collection-item">  <%=msg%> </li>
                <% end %>
              </ul>
          </div>
        <% end %>
         <div class="row ">
              <div class="input-field col s6">
                  <div class="field">
                        <i class="material-icons prefix">account_circle</i>
                        <%= f.text_field :name, class: "validate", id: "icon_prefix" %>
                        <label for="icon_prefix">Nombre</label>
                  </div>
              </div>
              <div class="input-field col s6">
                  <div class="field">
            
                    <i class="material-icons prefix">note_add</i>
                    <%= f.number_field :stock, class: "validate", id: "icon_prefix"  %>
                    <label for="icon_prefix"> Existencia </label>
                  </div>
              </div>
          </div>
     
        <div  style="font-size: 20px;">
               Unidad:
        </div>
        <br>
        <div class="row">
            <div class="input-field col s6">
              <div class="field">
                <%= f.select :measurement_unit_id, options_for_select(measurement_for_select) %>
              </div>
            </div>
        </div>
         <div class="actions">
              <%= f.submit "Guardar", :class => "btn waves-effect waves-light category-text"  %>
         </div>
<% end %>

MariscosSanJon/app/views/ingredients/edit.html.erb
<div class="container">
	<h5>Editar Ingrediente</h5>

	<%= render 'form' %>

	<%= link_to 'Mostrar', @ingredient, :class => "waves-effect waves-light btn category-text blue" %> 
	<%= link_to 'Regresar', ingredients_path,:class => "waves-effect waves-light btn category-text red" %>
</div>

MariscosSanJon/app/views/ingredients/index.html.erb
<% if(notice) %>
  <div class="card-panel">
        <span class="blue-text text-darken-2"><%= notice %> </span>
  </div>
<% end %>
<div class="container">
    <h5>Ingredientes</h5>

    <table width="60%">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Existencia</th>
          <th>Unidad de Medida </th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @ingredients.each do |ingredient| %>
          <tr>
            <td><%= ingredient.name %></td>
            <td><%= ingredient.stock %></td>
            <td><%= ingredient.measurement_unit.name %></td>
            <td><%= link_to 'Editar', edit_ingredient_path(ingredient), :class  => "waves-effect waves-light btn category-text blue" %></td>
            <td><%= link_to 'Eliminar', ingredient, method: :delete, data: { confirm: 'Seguro que deseas Eliminar?' }, :class => "waves-effect waves-light btn category-text red" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Agregar Ingrediente', new_ingredient_path, :class => "waves-effect waves-light btn category-text" %>
</div>

MariscosSanJon/app/views/ingredients/new.html.erb
<div class="container">
	<h5>Nuevo Ingrediente</h5>

	<%= render 'form' %>

		<%= link_to 'Regresar', ingredients_path, class: "waves-effect waves-light btn red category-text" %>

</div>

MariscosSanJon/app/views/ingredients/show.html.erb
<% if(notice) %>
  <div class="card-panel">
        <span class="blue-text text-darken-2"><%= notice %> </span>
  </div>
<% end %>
<div class="container">
	<p>
	  <strong>Name:</strong>
	  <%= @ingredient.name %>
	</p>

	<p>
	  <strong>Stock:</strong>
	  <%= @ingredient.stock %>
	</p>

	<p>
	  <strong>Measurement unit:</strong>
	  <%= @ingredient.measurement_unit.name %>
	</p>

	<%= link_to 'Editar', edit_ingredient_path(@ingredient), :class => "waves-effect waves-light btn category-text" %> 
	<%= link_to 'Regresar', ingredients_path,:class => " waves-effect waves-light btn red category-text" %>
</div>

MariscosSanJon/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MariscosSanJon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
 
</head>
<body>

<%= yield %>

</body>
</html>

MariscosSanJon/app/views/measurement_units/_form.html.erb
<div class="row"> 
    <div class="col s12">
        <%= form_for(@measurement_unit) do |f| %>
          <% if @measurement_unit.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@measurement_unit.errors.count, "error") %>  el elemento de medida no puede ser guardado </h2>
              <ul class="collection">
                <% @measurement_unit.errors.each do |attr,msg|  %>
                   <li class="collection-item">  <%=msg%> </li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row ">
             <div class="input-field col s6">
                <div class="field">
                   <i class="material-icons prefix">account_circle</i>
                   <%= f.text_field :name  ,class: "validate", id: "icon_prefix" %>
                   <label for="icon_prefix">Nombre</label>
                </div>
             </div>
          </div>
          <div class="actions">
                <%= f.submit "Guardar", :class => "btn waves-effect waves-light category-text"  %> 
          </div>
        <% end %>
    </div>
</div>

MariscosSanJon/app/views/measurement_units/edit.html.erb
<div class="container">
	<h5>Editar</h5>

	<%= render 'form' %>

	<%= link_to 'Mostrar', @measurement_unit, :class => "waves-effect waves-light btn category-text blue" %> 
	<%= link_to 'Regresar', measurement_units_path,:class => "waves-effect waves-light btn category-text red" %>
</div>

MariscosSanJon/app/views/measurement_units/index.html.erb
<% if(notice) %>
  <div class="card-panel">
        <span class="blue-text text-darken-2"> <%= notice %> </span>
  </div>
<% end  %>
<div class="container">
<h5>Unidades de Medida</h5>
  <table width="70%">
    <thead>
      <tr>
        <th>Nombre Unidad </th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @measurement_units.each do |measurement_unit| %>
        <tr>
          <td><%= measurement_unit.name %></td>
          <td><%= link_to 'Editar', edit_measurement_unit_path(measurement_unit), :class  => "waves-effect waves-light btn category-text blue" %></td>
          <td><%= link_to 'Eliminar', measurement_unit, method: :delete, data: { confirm: 'Seguro que deseas eliminar?' }, :class => "waves-effect waves-light btn category-text red" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nueva Unidad de Medida', new_measurement_unit_path, :class => "waves-effect waves-light btn category-text" %>
</div>

MariscosSanJon/app/views/measurement_units/new.html.erb
<div class="container">
	<h5>Nueva Unidad de Medida</h5>

	<%= render 'form' %>

	<%= link_to 'Regresar', measurement_units_path, class: "waves-effect waves-light btn red category-text" %>
</div>

MariscosSanJon/app/views/measurement_units/show.html.erb
<div class="container">
	<% if(notice) %>
		<div class="card-panel">
		      <span class="blue-text text-darken-2"><%= notice %> </span>
		</div>
	<% end %>
	<p>
	  <strong> Nombre: </strong>
	  <%= @measurement_unit.name %>
	</p>

	<%= link_to 'Editar', edit_measurement_unit_path(@measurement_unit), :class => "waves-effect waves-light btn category-text" %> 
	<%= link_to 'Regresar', measurement_units_path,:class => " waves-effect waves-light btn red category-text" %>
</div>